AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - bin/**
    - spec/spec_helper.rb
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: true
  Max: 160
Metrics/AbcSize:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
    - scenario
    - it
    - feature
